### ISSUE TITLE
How to View Error Log?

### ISSUE THREAD

**Issue by GregLancaster71** [squizlabs/sublime-PHP_CodeSniffer#2]
In the documentation you show a screenshot of a pretty error log, in what appears to be the console.  When I sniff a file, I do not get any error log.  Nor do I get one if I use cs-fixer or phpcb.

**Comment by sertand** [comment]
Do you see any errors in the Sublime Text's console (View -> Show Console)?

**Comment by GregLancaster71** [comment]
Yes, but they are formatted like <error etc etc>.  They dont look as pretty as yours.

**Comment by gsherwood** [comment]
Are you sure you are using this particular plugin? It doesn't have support for the php-cs-fixer tool. It only supports PHPCS and PHPCBF.

Are you using this one instead? https://github.com/benmatselby/sublime-phpcs

**Comment by chris0147** [comment]
Hey Greg, I have sent you an email did you get them? please reply as i really want talk to you over about something related to my PE problem.

**Comment by gsherwood** [comment]
> Hey Greg, I have sent you an email did you get them?

I don't think I've got anything from you. Email me directly: gsherwood at squiz dot net

**Comment by chris0147** [comment]
@gsherwood I am not talking to you, I'm talking to GregLancaster71 okay.

**Comment by gsherwood** [comment]
> I'm talking to GregLancaster71 okay

Okay. Might be best to use usernames in the comments then.

**Comment by chris0147** [comment]
@GregLancaster71 have you got my email? please answer it i want to speak to you about something that is important....

**Comment by chris0147** [comment]
@GregLancaster71 have you got my email? please answer it i want to speak to you about something that is important....

**Comment by chris0147** [comment]
@GregLancaster71 have you got my email? please answer it i want to speak to you about something that is important....
